version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "umschooldb"
      POSTGRES_USER: "umschooluser"
      POSTGRES_PASSWORD: "umschoolpswd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - umschooldb-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.13
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpswd"
      PGADMIN_CONFIG_SERVER_MODE: "False" # To allow running in desktop mode
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

volumes:
  umschooldb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge